version: '3.0'

services:
  backend:
    image: kodecupid/django
    container_name: kodecupid-django
    ports:
      - ${KODECUPID_BACKEND_PORT}:${KODECUPID_BACKEND_PORT}
    volumes:
      - ./backend/:/files
    working_dir: /files
    build:
      context: ./docker-images/django/
      dockerfile: Dockerfile
      args:
        user_name: ${DOCKER_USER}
        user_id: ${DOCKER_USER_ID}
        grp_id: ${DOCKER_GRP_ID}
        debug: ${KODECUPID_DEBUG}
    env_file: 
      - .env
    user: $DOCKER_USER_ID:$DOCKER_GRP_ID
    depends_on:
      - database

  frontend:
    image: kodecupid/vuejs
    container_name: kodecupid-vuejs
    ports:
      - ${KODECUPID_FRONTEND_PORT}:${KODECUPID_FRONTEND_PORT}
    volumes:
      - ./frontend/:/files
    working_dir: /files
    build:
      context: ./docker-images/vuejs/
      dockerfile: Dockerfile
      args:
        user_name: ${DOCKER_USER}
        user_id: ${DOCKER_USER_ID}
        grp_id: ${DOCKER_GRP_ID}
        debug: ${KODECUPID_DEBUG}
    env_file: 
      - .env
    user: $DOCKER_USER_ID:$DOCKER_GRP_ID
    depends_on:
      - backend


  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${KODECUPID_DATABASE_PASSWORD}
      POSTGRES_USER: ${KODECUPID_DATABASE_USER}
      POSTGRES_DB: ${KODECUPID_DATABASE_NAME}
    ports:
      - ${KODECUPID_DATABASE_PORT}:${KODECUPID_DATABASE_PORT}
    
    