# Generated by Django 5.0.3 on 2024-03-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0002_alter_user_pfp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('source_user', 'target_user'), name='unique_like'),
        ),
    ]
