# Generated by Django 5.0.4 on 2024-04-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0003_like_unique_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='kodecupidapp.tag'),
        ),
    ]
