# Generated by Django 5.0.4 on 2024-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0004_remove_tag_users_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='looking_for',
            field=models.BooleanField(),
        ),
    ]
