# Generated by Django 5.0.4 on 2024-04-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0005_user_sex_alter_user_looking_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='looking_for',
        ),
    ]
