# Generated by Django 5.0.4 on 2024-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0006_remove_user_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
