# Generated by Django 5.0.4 on 2024-04-26 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0007_user_looking_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_target_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
