# Generated by Django 5.0.4 on 2024-05-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfp', to='kodecupidapp.picture'),
        ),
    ]
