# Generated by Django 5.0.4 on 2024-05-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecupidapp', '0009_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=255),
        ),
    ]
